import moment from 'moment';
import React, { useState } from 'react'
import { useForm } from 'react-hook-form';
import Backbutton from '../../components/backbutton';
import { formatter2 } from '../../utils/formatter';


export default function JournalDefinition() {
    const { register, handleSubmit, formState: { errors }, reset, watch, trigger, control, setValue } = useForm({
        mode: "onChange",
        reValidateMode: 'onChange'
    });
    const { register: register2, formState: { errors: errors2 }, setValue: setValue2, reset: reset2, getValues: getValues2 } = useForm({
        mode: "onChange",
        reValidateMode: 'onChange'
    });

    const [journalDefinition, setJournalDefinition] = useState({
        id: 1,
        journalDescription: "",
        transactionDate: "",
        remark: "",
        autoGenerated: false,
        canAddMoreItems: false,
        canRemoveMoreItems: false
    })
    const [journalDefinitionDetails, setJournalDefinitionDetails] = useState([])
    const [addJournalDefinitionDetails, setAddJournalDefinitionDetails] = useState({
        accountCode: "",
        amount: 0,
        isCredited: false,
        compulsory: false,
        canChangeAccountCode: false,
        canChangeIsCredited: false,
        canChangeAmount: false,
    })

    const handleOnChange = (e) => {
        let { name, value, checked } = e.target
        setJournalDefinition({
            ...journalDefinition,
            [name]: value === 'on' ? checked : value ?? JSON.parse(value),
        })

    }
    console.log({ journalDefinition })

    const handleOnChange2 = (e) => {
        let { name, value } = e.target
        if (name === "debit" || name === "credit") {
            if (value === "") {
                if (name === "debit") {
                    setValue2("debit", value)
                } else {
                    setValue2("credit", value)
                }
            }
            else {
                const num = parseFloat(value.replace(/,/g, ''));
                const numm = (formatter2.format((num)))
                if (name === "debit") {
                    setValue2("debit", numm === "NaN" ? 0 : numm)
                } else {
                    setValue2("credit", numm === "NaN" ? 0 : numm)
                }
            }
        }


        setAddJournalDefinitionDetails({
            ...addJournalDefinitionDetails,
            [name]: value ?? JSON.parse(value),
        })
    }

    const addToJournalDetails = () => {
        const journ = {
            journalId: journalDefinition.id,
            journalDescription: addJournalDefinitionDetails.journalDescription,
            transactionDate: addJournalDefinitionDetails.transactionDate,
            remark: addJournalDefinitionDetails.remark,
            autoGenerated: addJournalDefinitionDetails.autoGenerated,
            canAddMoreItems: addJournalDefinitionDetails.canAddMoreItems,
            canRemoveMoreItems: addJournalDefinitionDetails.canRemoveMoreItems,
        }
        setJournalDefinitionDetails([...journalDefinitionDetails, journ]);
        reset2()

    }

    const deleteJournal = (journalDefinition) => {
        let exists = journalDefinitionDetails.find(x => x.journalId === journalDefinition.journalId);

        if (exists) {
            const filteredJournals = journalDefinitionDetails.filter(function (item) {
                return item.accountCode !== journalDefinition.accountCode;
            })
            setJournalDefinitionDetails([...filteredJournals]);
        }
    }

    const editJournal = (journalDefinition) => {
        setValue2("transactionNarration", journalDefinition.transactionNarration)
        setValue2("accountCode", journalDefinition.accountCode)
        setValue2("credit", formatter2.format(journalDefinition.credit))
        setValue2("debit", formatter2.format(journalDefinition.debit))
        setAddJournalDefinitionDetails(journalDefinition)
        const filteredJournals = journalDefinitionDetails.filter(function (item) {
            return item.accountCode !== journalDefinition.accountCode;
        })
        setJournalDefinitionDetails([...filteredJournals]);

    }

    const submitJournal = () => {
        const payload = {
            id: journalDefinition.id,
            transactionRef: journalDefinition.transactionRef,
            transactionDate: journalDefinition.transactionDate,
            narration: journalDefinition.narration,
            journalDescription: journalDefinition.journalDescription,
            source: journalDefinition.source,
            autoGenerated: journalDefinition.autoGenerated,
            approvedOn: new Date(),
            approvedBy: "Stephanie",
            journalDefinitionDetails: journalDefinitionDetails
        }
        console.log({ payload })
    }
    return (
        <>
            <div className="content-wrapper mt-5">
                <div className="card">
                    <div className="card-body">
                        <div className="d-flex align-items-center justify-content-between">
                            <div className="d-flex align-items-center justify-content-center flex-column">
                                {/* <img src="assets/images/logo-mini-1.png" /> */}
                                {/* <span className="h6 d-none d-md-block">NETOP CONSULTING</span> */}
                            </div>
                            <span className="card-title">JOURNAL DEFINITION</span>
                            <span className="mr-5 d-none d-md-block"></span>
                        </div>
                        <div className="d-flex align-items-right justify-content-between">
                            <Backbutton />
                            <button type="button" onClick={submitJournal}
                                class="btn btn-primary btn-sm btn-icon-text text-white d-flex float-right">
                                <i className="ti-save mr-1" title="Submit"></i>
                                <span className="d-none d-md-block">SUBMIT</span>
                            </button>

                        </div>

                        <form className="row newReceiptNote mt-5">
                            <div className="form-group col-md-3">
                                <label htmlFor="journalDescription">Journal Description<span className="text-danger">*</span>
                                    {errors.journalDescription &&
                                        <span className="text-danger font-weight-bold"> required</span>
                                    }
                                </label>
                                <input type="text" className="form-control form-control-sm"
                                    id="journalDescription"
                                    name="journalDescription"
                                    {...register("journalDescription", { required: true, onChange: (e) => { handleOnChange(e) } })}
                                    placeholder="Journal Description" />
                            </div>
                            <div className="form-group col-md-3">
                                <label htmlFor="remark">Remark<span className="text-danger">*</span>
                                    {errors.remark &&
                                        <span className="text-danger font-weight-bold">required</span>
                                    }
                                </label>
                                <input type="text" className="form-control form-control-sm"
                                    id="remark"
                                    name="remark"
                                    {...register("remark", { required: true, onChange: (e) => { handleOnChange(e) } })}
                                    placeholder="Remark" />
                            </div>
                            <div className="form-group col-md-3">
                                <label htmlFor="autoGenerated">Can Add More Items</label>
                                <div className="custom-control custom-switch">
                                    <input type="checkbox"
                                        className="custom-control-input"
                                        id="autoGenerated"
                                        name="autoGenerated"
                                        {...register("autoGenerated", { onChange: (e) => handleOnChange(e) })}
                                    />
                                    <label className="custom-control-label" htmlFor="autoGenerated"></label>
                                </div>
                            </div>
                            <div className="form-group col-md-3">
                                <label htmlFor="autoGenerated">Auto Generated</label>
                                <div className="custom-control custom-switch">
                                    <input type="checkbox"
                                        className="custom-control-input"
                                        id="autoGenerated"
                                        name="autoGenerated"
                                        {...register("autoGenerated", { onChange: (e) => handleOnChange(e) })}
                                    />
                                    <label className="custom-control-label" htmlFor="autoGenerated"></label>
                                </div>
                            </div>
                            <div className="form-group col-md-3">
                                <label htmlFor="autoGenerated">Auto Generated</label>
                                <div className="custom-control custom-switch">
                                    <input type="checkbox"
                                        className="custom-control-input"
                                        id="autoGenerated"
                                        name="autoGenerated"
                                        {...register("autoGenerated", { onChange: (e) => handleOnChange(e) })}
                                    />
                                    <label className="custom-control-label" htmlFor="autoGenerated"></label>
                                </div>
                            </div>

                            <div className="form-group col-md-3">
                                <label htmlFor="transactionDate">Transaction Date</label>
                                {errors.transactionDate && (
                                    <span className="text-danger"> required</span>
                                )}
                                <input
                                    type="date"
                                    className="form-control form-control-sm"
                                    id="transactionDate"
                                    name="transactionDate"
                                    placeholder="Expiry Date"
                                    {...register("transactionDate", {
                                        required: true,
                                        onChange: (e) => { handleOnChange(e) }
                                    })}
                                    min={moment().format("YYYY-MM-DD")}
                                />
                            </div>

                        </form>
                    </div>
                </div>

                <div className="card mt-2">
                    <div className="card-body">
                        <form className="row newReceiptNote ">
                            <div className="form-group col-md-3">
                                <label htmlFor="accountCode">Account Code
                                    {errors2.accountCode &&
                                        <span className="text-danger font-weight-bold"> required</span>
                                    }
                                </label>
                                <input type="text" className="form-control form-control-sm"
                                    id="accountCode"
                                    name="accountCode"
                                    {...register2("accountCode", { required: true, onChange: (e) => { handleOnChange2(e) } })}
                                    placeholder="Account Code" />
                            </div>
                            <div className="form-group col-md-3">
                                <label htmlFor="amount">Amount
                                    {errors2.amount &&
                                        <span className="text-danger font-weight-bold"> required</span>
                                    }
                                </label>
                                <input type="text" className="form-control form-control-sm"
                                    id="amount"
                                    name="amount"
                                    {...register2("amount", { required: true, onChange: (e) => { handleOnChange2(e) } })}
                                    placeholder="Amount" />
                            </div>

                        </form>
                        <button
                            type="submit"
                            onClick={() => addToJournalDetails()}
                            class="btn btn-primary btn-sm btn-icon-text text-white d-flex float-right"
                        // disabled={loading ? true : false}
                        >
                            <i className=" mdi mdi-plus mr-1" title="Submit"></i>
                            ADD
                        </button>

                    </div>
                </div>

                <div className="row mt-1">
                    <div className="col-md-12 grid-margin stretch-card">
                        <div className="card">
                            <div className="">
                                <div className='table-responsive'>
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>
                                                    S/N
                                                </th>
                                                <th>
                                                    TRANSACTION NARRATION
                                                </th>
                                                <th>
                                                    ACCOUNT CODE
                                                </th>
                                                <th>
                                                    DEBIT
                                                </th>
                                                <th>
                                                    CREDIT
                                                </th>
                                                <th>
                                                    ACTION
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {journalDefinitionDetails &&
                                                journalDefinitionDetails.map((journal, index) =>
                                                    <tr className="py-0">
                                                        <td >
                                                            {index + 1}
                                                        </td>
                                                        <td>
                                                            {journal.transactionNarration}
                                                        </td>
                                                        <td>
                                                            {journal.accountCode}
                                                        </td>
                                                        <td>
                                                            {formatter2.format(journal.debit)}
                                                        </td>
                                                        <td>
                                                            {formatter2.format(journal.credit)}
                                                        </td>
                                                        <td>
                                                            <div className="d-flex justify-content-between">
                                                                {<i className="ti-pencil text-warning mr-3" onClick={() => editJournal(journal)} title="Edit" />}
                                                                <i className="ti-trash text-danger" onClick={() => deleteJournal(journal)} title="Delete" />
                                                            </div>
                                                        </td>
                                                    </tr>
                                                )}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
