export const journals = {
    totalCount:3,
    data: [
    {
        approvedBy: "",
        approvedOn: "Tue Jul 05 2022 11:40:42 GMT+0100 (West Africa Standard Time)",
        autoGenerated: true,
        id: 1,
        journalDescription: "ok",
        narration: "ok",
        source: "Sales System",
        transactionDate: "2022-07-07",
        transactionRef: "JOUR-001",
        journalDetails: [
            {
                accountCode: "8988998",
                credit: 200000,
                debit: 30000,
                journalId: 1,
                transactionNarration: "ok",

            },
            {
                accountCode: "7899990",
                credit: 0,
                debit: 300000,
                journalId: 1,
                transactionNarration: "the good left",
            },
            {
                accountCode: "6788897",
                credit: 100000,
                debit: 0,
                journalId: 1,
                transactionNarration: "ok and ok",
            }
        ]
    },

    {
        approvedBy: "",
        approvedOn: "Tue Jul 05 2022 11:40:42 GMT+0100 (West Africa Standard Time)",
        autoGenerated: false,
        id: 2,
        journalDescription: "ok",
        narration: "ok",
        source: "Journal",
        transactionDate: "2022-07-09",
        transactionRef: "JOUR-002",
        journalDetails: [
            {
                accountCode: "6688789",
                credit: 100000,
                debit: 70000,
                journalId: 2,
                transactionNarration: "ok",

            },
            {
                accountCode: "5677837",
                credit: 2000,
                debit: 600000,
                journalId: 2,
                transactionNarration: "the good left",
            },
            {
                accountCode: "7837837",
                credit: 0,
                debit: 3000099,
                journalId: 2,
                transactionNarration: "ok and ok",
            }
        ]
    },

    {
        approvedBy: "Stephanie",
        approvedOn: "Tue Jul 05 2022 11:40:42 GMT+0100 (West Africa Standard Time)",
        autoGenerated: false,
        id: 3,
        journalDescription: "ok",
        narration: "ok",
        source: "Journal",
        transactionDate: "2022-08-09",
        transactionRef: "JOUR-003",
        journalDetails: [
            {
                accountCode: "6688789",
                credit: 100000,
                debit: 70000,
                journalId: 3,
                transactionNarration: "ok",

            },
            {
                accountCode: "5677837",
                credit: 2000,
                debit: 647880,
                journalId: 3,
                transactionNarration: "the good",
            },
            {
                accountCode: "7837837",
                credit: 200000,
                debit: 600870,
                journalId: 3,
                transactionNarration: "ok best",
            }
        ]
    },
]
}